// src/routes/history/+page.svelte
<script>
    import VideoEmbed from '$lib/components/VideoEmbed.svelte';
    import '../../lib/styles/global.css';
</script>

<!-- Enhanced Hero Section -->
<section class="history-hero">
    <div class="hero-content">
        <h1>History & Future of the Telephone</h1>
        <p>Explore the evolution of public communication from the invention of the telephone to the next leap with Starphone.</p>
    </div>
    <div class="givebutter-donate">
        <givebutter-widget id="LYxbKj"></givebutter-widget>
        <script async src="https://widgets.givebutter.com/latest.umd.cjs?acct=dOQ0XbCHnxsv4qWo&p=other"></script>
    </div>
</section>

<!-- Enhanced Timeline Section -->
<section class="history-timeline section">
    <div class="container">
        <h2>The Journey of Public Phone and Starphone</h2>
        <div class="timeline">
            <div class="timeline-item">
                <h3>1876</h3>
                <p>Invention of the Telephone</p>
            </div>
            <div class="timeline-item">
                <h3>1889</h3>
                <p>First Public Telephone Installed in Connecticut</p>
            </div>
            <div class="timeline-item">
                <h3>1900s</h3>
                <p>Expansion of Telephone Networks Worldwide</p>
            </div>
            <div class="timeline-item">
                <h3>1960s</h3>
                <p>Public Telephones Become Common in Cities</p>
            </div>
            <div class="timeline-item">
                <h3>1980s</h3>
                <p>Peak of Public Telephone Usage</p>
            </div>
            <div class="timeline-item">
                <h3>2000s</h3>
                <p>Decline of Public Telephones with Mobile Phones</p>
            </div>
            <div class="timeline-item">
                <h3>2024</h3>
                <p>Introduction of Starphone: The Next Evolution</p>
            </div>
            <div class="timeline-item">
                <h3>2025</h3>
                <p>Starphone Prototype Finalized</p>
            </div>
            <div class="timeline-item">
                <h3>2026</h3>
                <p>Starphone Expands to Major Cities and Rural Areas</p>
            </div>
            <div class="timeline-item">
                <h3>2027</h3>
                <p>Starphone on the Moon</p>
            </div>
            <div class="timeline-item">
                <h3>2028</h3>
                <p>Space Stations Equipped with Starphones</p>
            </div>
            <div class="timeline-item">
                <h3>2030</h3>
                <p>Interplanetary Communication Powered by Starphone</p>
            </div>
        </div>
    </div>
</section>

<!-- Enhanced Technology Section -->
<section class="technology-section section">
    <div class="container">
        <h2>The Technology Behind Starphone</h2>
        <div class="tech-features">
            <div class="tech-item">
                <h3>Faraday Cage Protection</h3>
                <p>Starphone's outer shell blocks electromagnetic interference, ensuring secure communication in high-EMI environments.</p>
            </div>
            <div class="tech-item">
                <h3>Hybrid Network System</h3>
                <p>Switch between satellite, cellular, and VoIP networks for constant connectivity.</p>
            </div>
            <div class="tech-item">
                <h3>Space-Grade Engineering</h3>
                <p>Radiation-resistant components and solar-powered autonomy allow Starphone to operate in the most extreme environments.</p>
            </div>
        </div>
    </div>
</section>

<!-- Call to Action Section -->
<section class="call-to-action section">
    <div class="container">
        <h2>Join the Movement</h2>
        <p>Be a part of something bigger. Whether you're an engineer, designer, or visionary, PH3AR and Starphone are looking for talented people to help shape the future of communication.</p>
        <a href="/support" class="button">Support Us</a>
    </div>
</section>
<!-- Enhanced Community Section -->
<section class="about-community section">
    <div class="container">
        <h2>PH3AR: Community & Collaboration</h2>
        <p>
            PH3AR is a growing community of technologists, engineers, and dreamers who work together to build impactful solutions. Starphone is one of our flagship projects, and it represents the spirit of collaboration and innovation that defines PH3AR.
        </p>
        <div class="community-grid">
            <div class="community-quote">
                <blockquote>
                    "PH3AR isn’t just a community. It’s a place where ideas come alive, and Starphone is a testament to that innovation."
                </blockquote>
                <cite>— PH3AR Member</cite>
            </div>
        </div>

<style>
    /* Enhanced Hero Section */
    .history-hero {
        background-color: var(--color-primary-dark);
        color: var(--color-button-text);
        text-align: center;
        padding: 80px 0;
    }

    .hero-content {
        max-width: 800px;
        margin: 0 auto;
        background: rgba(0, 0, 0, 0.6);
        padding: 20px;
        border-radius: 8px;
    }

    .hero-content h1 {
        font-size: 2.5rem;
        margin-bottom: 20px;
    }

    .hero-content p {
        font-size: 1.2rem;
    }

    /* Section Spacing */
    .section {
        padding: 60px 0;
    }

    /* Timeline Section */
    .history-timeline {
        background-color: var(--color-background);
        color: var(--color-text);
    }

    .timeline {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
        gap: 20px;
    }

    .timeline-item {
        background-color: var(--color-secondary);
        padding: 20px;
        text-align: center;
        border-radius: var(--border-radius);
        box-shadow: var(--box-shadow);
    }

    .timeline-item h3 {
        color: var(--color-primary-dark);
        margin-bottom: 10px;
    }

    .timeline-item p {
        font-size: 1.1rem;
        color: var(--color-text-light);
    }

    /* Technology Section */
    .technology-section .tech-features {
        display: flex;
        justify-content: space-between;
        gap: 20px;
        flex-wrap: wrap;
    }

    .tech-item {
        flex: 1;
        text-align: center;
        background-color: var(--color-secondary);
        padding: 20px;
        border-radius: var(--border-radius);
        min-width: 220px;
    }

    .tech-item h3 {
        color: var(--color-primary-dark);
    }

    /* Call to Action Section */
    .call-to-action {
        background-color: var(--color-primary);
        text-align: center;
        color: var(--color-button-text);
    }

    .call-to-action h2 {
        font-size: 2rem;
        margin-bottom: 20px;
    }

    .call-to-action p {
        font-size: 1rem;
        margin-bottom: 30px;
    }

    .call-to-action .button {
        background-color: var(--color-secondary);
        color: var(--color-button-text);
        padding: 12px 24px;
        border-radius: 8px;
        text-decoration: none;
        transition: background-color var(--transition-speed) ease;
    }

    .call-to-action .button:hover {
        background-color: var(--color-secondary-dark);
    }

    /* Media Queries */
    @media (max-width: 768px) {
        .hero-content h1 {
            font-size: 2rem;
        }

        .hero-content p {
            font-size: 1rem;
        }

        .timeline {
            grid-template-columns: 1fr;
        }

        .tech-features {
            flex-direction: column;
        }
    }

    @media (max-width: 480px) {
        .hero-content h1 {
            font-size: 1.8rem;
        }

        .hero-content p {
            font-size: 0.9rem;
        }

        .call-to-action h2 {
            font-size: 1.8rem;
        }

        .call-to-action p {
            font-size: 0.9rem;
        }
    }
</style>

// app/history/page.tsx
import type { Metadata } from 'next';
import styles from './history.module.css';

export const metadata: Metadata = {
  title: 'History | Starphone Development Journey',
  description: 'Discover the history and evolution of Starphone from initial concept to deployed communication systems. See our milestones and achievements.',
  openGraph: {
    title: 'History | Starphone Development Journey',
    description: 'The story of Starphone\'s journey from concept to reality.',
    url: 'https://www.thestarphone.com/history',
  },
};

export default function HistoryPage() {
  return (
    <div className={styles.historyPage}>
      <section className={styles.hero}>
        <div className={styles.container}>
          <h1>History & Future of Communication</h1>
          <p className={styles.heroSubtitle}>Explore the evolution of public communication from the invention of the telephone to the next leap with Starphone</p>
        </div>
      </section>

      <section className={styles.timeline}>
        <div className={styles.container}>
          <h2>The Journey of Public Phone and Starphone</h2>
          <div className={styles.timelineTrack}>
            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>📞</div>
              <div className={styles.timelineContent}>
                <h3>1876 - Invention of the Telephone</h3>
                <p>Alexander Graham Bell invents the telephone, revolutionizing human communication forever.</p>
              </div>
            </div>
            
            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🏛️</div>
              <div className={styles.timelineContent}>
                <h3>1889 - First Public Telephone</h3>
                <p>First public telephone installed in Connecticut, making communication accessible to everyone.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🌍</div>
              <div className={styles.timelineContent}>
                <h3>1900s - Global Expansion</h3>
                <p>Expansion of telephone networks worldwide, connecting continents and cultures.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🏙️</div>
              <div className={styles.timelineContent}>
                <h3>1960s - Urban Revolution</h3>
                <p>Public telephones become common in cities, making communication accessible on every street corner.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>📈</div>
              <div className={styles.timelineContent}>
                <h3>1980s - Peak Usage</h3>
                <p>Peak of public telephone usage as they become essential urban infrastructure.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>📱</div>
              <div className={styles.timelineContent}>
                <h3>2000s - Mobile Era</h3>
                <p>Decline of public telephones with the rise of mobile phones, but a gap emerges for reliable public infrastructure.</p>
              </div>
            </div>
            
            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🎯</div>
              <div className={styles.timelineContent}>
                <h3>2023 - The Vision</h3>
                <p>Starphone was conceived with a bold vision: to revolutionize public communication and make it reliable even in the most extreme environments.</p>
              </div>
            </div>
            
            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🔨</div>
              <div className={styles.timelineContent}>
                <h3>October 2023 - First Prototype</h3>
                <p>Our first public phone booth prototype was built from cardboard and laser-cut panels. The prototype was deployed near SpaceX Starbase and received its first calls from visitors including Darwin from Canada, proving the concept works in real-world conditions.</p>
              </div>
            </div>
            
            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🌪️</div>
              <div className={styles.timelineContent}>
                <h3>2023-2024 - Extreme Testing</h3>
                <p>The booth withstood extreme weather conditions including high winds near SpaceX launches and harsh Texas weather. Post-IFT3, we didn&apos;t think it would survive, but it did! We tested at remote locations including Shenandoah National Park and gathered valuable real-world data.</p>
              </div>
            </div>
            
            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>📡</div>
              <div className={styles.timelineContent}>
                <h3>2024 - Enhanced Systems</h3>
                <p>Added IoT environmental sensors, improved network redundancy with Starlink and cellular, and developed enhanced security protocols. Participated in Maker Faire Alexandria and FEMA demonstrations. The stainless steel booth prototype was completed.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🚀</div>
              <div className={styles.timelineContent}>
                <h3>2025 - Prototype Finalized</h3>
                <p>Starphone prototype finalized with space-grade engineering and ready for deployment.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🌐</div>
              <div className={styles.timelineContent}>
                <h3>2026 - Expansion</h3>
                <p>Starphone expands to major cities and rural areas, providing reliable communication infrastructure.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🌙</div>
              <div className={styles.timelineContent}>
                <h3>2027 - Starphone on the Moon</h3>
                <p>First Starphone deployed for lunar communications.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🛰️</div>
              <div className={styles.timelineContent}>
                <h3>2028 - Space Stations</h3>
                <p>Space stations equipped with Starphones for reliable crew communication.</p>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker}>🪐</div>
              <div className={styles.timelineContent}>
                <h3>2030 - Interplanetary</h3>
                <p>Interplanetary communication powered by Starphone, connecting humanity across the solar system.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* PH3AR Community Section */}
      <section className={styles.community}>
        <div className={styles.container}>
          <h2>PH3AR: Community & Collaboration</h2>
          <p className={styles.communityIntro}>
            PH3AR is a growing community of technologists, engineers, geeks, gamers and dreamers who work together and play together. Starphone is one of our flagship projects, and it represents the spirit of collaboration and innovation that defines PH3AR.
          </p>
          <div className={styles.communityQuote}>
            <blockquote>
              &quot;PH3AR isn&apos;t just a community. It&apos;s a place where ideas come alive, and Starphone is a testament to that innovation.&quot;
            </blockquote>
            <cite>— PH3AR Member</cite>
          </div>
          <div className={styles.ctaActions}>
            <a href="https://www.ph3ar.com/about" target="_blank" rel="noopener noreferrer" className={styles.ctaButton}>
              Learn About PH3AR
            </a>
            <a href="/support" className={styles.ctaButtonSecondary}>
              Support the Mission
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}
